modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/yourname/vivids"

[[mods]]
modId="vivids"
version="${file.jarVersion}"
displayName="Vivids"
authors="You"
description='''
Vivids - criaturas amigables, una dimension del bano, jefes raros y armas de energia.
'''

[[dependencies.vivids]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vivids]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
